### PR TITLE
Enable simuling components

### PR DESCRIPTION
**Pull request by N1coc4colA**
Enabling simulation of components (as some already do in a peculiar manner), with finer control can be good when not having the required HW parts.

### CODE REVIEW

**Comment by Shaft-3796** [comment]
I don't know if you have seen it but this is already done for sim7600 vl53 and sense hat. Everything is detected automatically and if needed components are emulated.

**Comment by Shaft-3796** [comment]
I did a lot of refactoring to increase codebase quality including this feature, this is pushed to develop not main.

**Comment by N1coc4colA** [comment]
The intent here is to control things in a more proper way. For example with vl53 it's just looking if we can establish I2C and all that goes with, if not, we simulate. However, in the case of a failure on the plane itself and we don't notice a thing, all the data we'll get, or some, is simulated data. I've seen there's additional stuff to tell it's simulated data.
However, to my eyes it's more relevant to just have data or nothing at all, or say that we explicitly want some simulated.

**Comment by Shaft-3796** [comment]
I understand, we will have to discuss about it ! However I don't think it's a problem since it does not matter if no data at all is streamed if there is an error or if emulated data is, the data consumer will **always** have to check that the data is healthy so the behaviors for a consumer won't change with this feature. And this feature add a layer of configuration and a risk if we do not configure correctly.

**Comment by Shaft-3796** [comment]
Closed it for now after our discussion, we will see later if we need this feature.

**Pull request closed without merging**
